-- 001. Revising the Select Query I
SELECT * FROM CITY WHERE COUNTRYCODE = 'USA' AND POPULATION > 100000;

-- 002. Revising the Select Query II
SELECT NAME FROM CITY WHERE COUNTRYCODE = 'USA' AND POPULATION > 120000;

-- 003. Select All
SELECT * FROM CITY;

-- 004. Select By ID
SELECT * FROM CITY WHERE id='1661';

-- 005. Japanese Cities' Attributes
SELECT * FROM CITY WHERE COUNTRYCODE='JPN';

-- 006. Japanese Cities' Names
SELECT NAME FROM CITY WHERE COUNTRYCODE='JPN';

-- 007. Weather Observation Station 1
SELECT CITY,STATE FROM STATION;